### ISSUE TITLE
Multi-cluster support for installing, upgrading and browsing apps across clusters

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#1753]
Over the past 6 months we've had various requests for multi-cluster support. A [proposal has been documented](https://docs.google.com/document/d/1-6cKxOsW6K5u3lK7Om2zQeVYVPxzHT6dVwej5wy3_9A/edit#) for discussion and is currently getting feedback from various people within VMware and within the community while we fill out the actual planned changes.

This issue will serve as an umbrella for more specific planned changes (below), starting with those that are the least contentious.

- [x] Configuration support for additional clusters #1752
- [x] Update kubeops deployment to support multi-cluster #1761 
- [x] Multi-cluster UX integration #1762 
- [x] Available namespace support on other clusters #1763 
- [x] Fail installation if non-oidc with multi-cluster attempted #1917
- [x] Documentation, demo and publicizing #1764
