### ISSUE TITLE
Pre-release of Kubeapps 2.0

### ISSUE THREAD

**Issue by andresmgot** [kubeapps/kubeapps#2028]
### Description:

The goal of this issue is to gather requirements we need to fulfill before cutting a release candidate for Kubeapps 2.0. We are targeting September 23th to make the new version available. We can split the issues to finish if they need changes in the code base or not:

**Codebase related:**
 - [x] Finish improvements/bug fixes planned in #1907 related to the new UI.
 - [x] [Multi-cluster] Auth to asset service fails #2026
 - [x] [Upgrade Flow] Allow to select global or namespaced repositories #1987
 - [x] Remove flag and support for Helm v2
 - [x] Remove flag and support for MongoDB
 - [x] Remove feature flag for Operators
 - [x] Upgrade PostgreSQL dependency
 - [x] Migrate e2e tests
 - [x] Upgrade Helm dependency (v3.3.2 - Security patch)

**Documentation and Promotion**
 - [x] Documentation for Multicluster setup #1764
 - [x] Demo video for Multicluster setup #1764
 - [x] Update current documentation to reflect new UI
 - [x] Demo video presenting the new UI
 - [x] Update kubeapps.com
 - [x] Upgrade from 1.11 guide

**Comment by andresmgot** [comment]
Everything done here :) Kubeapps 2.0.0-beta.2 already available.
