### ISSUE TITLE
Documentation to setup and configure Kubeapps 2.3.2 capabilities

### ISSUE THREAD

**Issue by ppbaena** [kubeapps/kubeapps#2778]
- [x] Kubeapps to be delivered as a Helm Chart that can be deployed in a TKG workload cluster (c.f. [guide §2.4](https://github.com/kubeapps/kubeapps/blob/865b28c0ccce0db421daa515509c947d808ced36/docs/step-by-step/kubeapps-on-tkg/step-2.md#24---installing-kubeapps-in-the-cluster))
- [x] Support SSO for AuthN with TKG using Pinniped  (c.f. [guide §2.2](https://github.com/kubeapps/kubeapps/blob/865b28c0ccce0db421daa515509c947d808ced36/docs/step-by-step/kubeapps-on-tkg/step-2.md#22---authentication))
- [x] Ability to configure TAC as a private Chart repo (c.f. [guide §3.2](https://github.com/kubeapps/kubeapps/blob/865b28c0ccce0db421daa515509c947d808ced36/docs/step-by-step/kubeapps-on-tkg/step-3.md#32---adding-the-vmware-tanzu-application-catalog-for-tanzu-advanced))
- [x] Ability to configure Marketplace as a public Chart repo (c.f. [guide §3.1](https://github.com/kubeapps/kubeapps/blob/865b28c0ccce0db421daa515509c947d808ced36/docs/step-by-step/kubeapps-on-tkg/step-3.md#31---adding-the-vmware-marketplace))
- [x] Support Clarity look and feel with a custom skin for Kubeapps (c.f. [guide §2.3](https://github.com/kubeapps/kubeapps/blob/865b28c0ccce0db421daa515509c947d808ced36/docs/step-by-step/kubeapps-on-tkg/step-2.md#23---look-and-feel-optional))
- [x] Tested and validated on the latest version of TKG (c.f. [guide §1.1](https://github.com/kubeapps/kubeapps/blob/865b28c0ccce0db421daa515509c947d808ced36/docs/step-by-step/kubeapps-on-tkg/step-1.md#11---install-a-recent-pinniped-version))

_Edited by @antgamdia_

**Comment by antgamdia** [comment]
The internal documentation is twofold: [user-faced documentation](https://github.com/kubeapps/kubeapps/tree/master/docs/user) and [dev docs](https://github.com/kubeapps/kubeapps/tree/master/docs/developer):

The developer documentation comprises:

- README.md: general overview of the Kubeapps components
  - apprepository-controller.md
  - asset-syncer.md
  - assetsvc.md
  - dashboard.md
  - kubeops.md
  - pinniped-proxy.md
- Advanced features:
  - basic-form-support.md
  - custom-form-component-support.md
  - translate-kubeapps.md
  - update-api-docs.md
- Building the project:
  - build.md
  - testing-environment.md
  - using-makefiles.md
- CI process:
  - ci.md
  - end-to-end-tests.md
  - release-process.md
- architecture/overview.md (outdated)

**Comment by antgamdia** [comment]
The user documentation includes:

- [access-control.md](https://github.com/kubeapps/kubeapps/blob/master/docs/user/access-control.md): general overview about the service-account and oidc configuration modes. Some RBAC examples. Needs improvement IMHO.
- [dashboard.md](https://github.com/kubeapps/kubeapps/blob/master/docs/user/dashboard.md): bunch of screenshots explaining how to use the dashboard.
- [deploying-to-multiple-clusters.md](https://github.com/kubeapps/kubeapps/blob/master/docs/user/deploying-to-multiple-clusters.md): how to configure OIDC, how to add a new cluster in kubeapps, and how to run a local multi-cluster development environment.
- [getting-started.md](https://github.com/kubeapps/kubeapps/blob/master/docs/user/getting-started.md): step by step guide on how to install Kubeapps, create a demo credential, access the dashboard, deploy WordPress, uninstall it.
- [offline-installation.md](https://github.com/kubeapps/kubeapps/blob/master/docs/user/offline-installation.md): how to install kubeapps in airgapped environments
- [operators.md](https://github.com/kubeapps/kubeapps/blob/master/docs/user/operators.md): step by step guide on how to install the OLM, install an operator, deploy the resources it provides 
- [private-app-repository.md](https://github.com/kubeapps/kubeapps/blob/master/docs/user/private-app-repository.md): guide on how to add a private repo and use the filtering. Then it shows how to configure ChartMuseum, Harbor, Habor OCI registry, Artifactory.
- [syncing-apprepository-webhook.md](https://github.com/kubeapps/kubeapps/blob/master/docs/user/syncing-apprepository-webhook.md): simple guide on how to configure a (harbor) webhook to trigger a repo re-sync.
- [using-an-OIDC-provider.md](https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md): general guide on how to configure OIDC with different providers (Keycloak, Dex, Azure Active Directory, Google OIDC, VMware Cloud Services), deploying an auth proxy (default and external), and debugging auth failures
- [using-an-OIDC-provider-with-pinniped.md](https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider-with-pinniped.md): supposing pinniped is up and running, guide on how to configure kubeapps to use pinniped with any oidc provider
