### ISSUE TITLE
Enable flux plugin to be used from Kubeapps UX

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#3610]
### Description:

While Greg's done a great job on the fluxv2 plugin itself, we have not yet used it from the Kubeapps UI. This issue is to identify and fix those issues so that others can use Kubeapps with flux.

I expect this list to grow a little as we work through the functionality, but feel free to put your initials next to an item if you want to grab it. To run Kubeapps with the flux plugin only, I'm using the `deploy-dev-kubeapps` make target with the following local diff:

```diff
--- a/docs/user/manifests/kubeapps-local-dev-values.yaml
+++ b/docs/user/manifests/kubeapps-local-dev-values.yaml
@@ -15,6 +15,8 @@ postgresql:
   existingSecret: postgresql-db
 kubeappsapis:
   replicaCount: 1
+  enabledPlugins:
+    - fluxv2
 ingress:
   enabled: true
   hostname: localhost
@@ -27,3 +29,7 @@ ingress:
     nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
     # Required for ingress-nginx 1.0.0 for a valid ingress.
     kubernetes.io/ingress.class: nginx
+redis:
+  enabled: true
+  auth:
+    password: "testing"
```

## Issues

- [x] Plugin's GetAvailablePackageSummaries needs to handle UX request with cluster (MN: #3609 )
- [x] Available apps don't display due to non-empty repo filter requested by UX (MN: https://github.com/kubeapps/kubeapps/pull/3619)
- [x] Getting available package detail: `Unable to get the available package detail for the package "bitnami/apache" using the plugin "fluxv2.packages": rpc error: code = NotFound desc = no fully indexed repository [default/bitnami] has been found`. Issue is that currently dashboard assumes repo is either in the current namespace, or the global namespace. This is not the case with flux (or generally). Need to update URLs to always encode the namespace? (MN: #3628)
- [x] All other fluxv2 plugin operations must also support UX request with cluster (similar to previous, just tests and one-liner) GF: #3620 
- [x] Unable to deploy package via Helm due to incorrect namespace used for available package (MN: #3640)
- [x] `HelmRelease` resource created when deploying via UI is in the `kubeapps` namespace, though the helm release and resources are correctly in the target namespace (see additional info on #3640) 
- [x] UX tries to grab a helm release via kubeops directly after deploying (which it can't and shouldn't do either way, see additional info on #3640) (MN: #3686)
