### ISSUE TITLE
Remaining work for running Kubeapps with Flux

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#3695]
### Description:

With #3610 we're able to use flux from the Kubeapps UI with some limitations and missing documentation.

This issue is capturing the remaining work that can be picked up when other dependencies are completed.

- [x] Currently after deploying, the installed package details view does not yet include any of the resources (dependent on #3403) 
- [x] When creating an installed pkg, we try to fetch the resources before flux has created the actual helm release, resulting in a not-found error
- [x] After helm release has been created, but before flux finishes reconciling, we're displaying a plain warning about reconciliation in progress, even though we already have the resources and could be showing the progress chart. #4247 
- [x] After the reconciliation succeeds, the UI doesn't update the app info status, so the upgrade/delete buttons remain disabled. #4256 
- [x] The catalog of available packages for flux2 doesn't currently display the repository #4231
- [x] The status for installed packages on the application tiles is inconsistent (and leads to formatting issues) between flux and carvel. Fixed in #4326  
- [x] There is no documentation for configuring and using Kubeapps with Flux. Fixed with #4317 
- [x] When the catalog (available packages) is empty, the UX should not display "Manage App Repositories" unless either the helm plugin is enabled (for now) or the AppRepository API is implemented (#3496) and supported in the UX. For now it'd be better to display a link to the documentation (above) so that we can (for now) have instructions about manually adding to the catalog when using flux (ie. adding a `HelmRepository`). #4331 
- [x] error if both helm and flux are selected for now
- [x] Update chart so that redis is deployed automatically if flux plugin enabled. Created subtask #4264 to discuss options.
- [x] Update chart so that postgres is only deployed if helm plugin is selected - https://github.com/bitnami/charts/pull/9204
- [x] Trying to deploy with unprivileged service account has unhelpful message. #4333
- [x] When flux cannot deploy helm chart, helmrelease CR remains pending but getresourcerefs eventually 404s as the actual helm release isn't created. Fixed in #4338 
- [ ] Use more user-faced `UserReason` fields (eg. currently we use `InstallFailed`, but we should at least add a space) [added by agamez]
